version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./weather.db:/app/weather.db
    environment:
      - FLASK_ENV=development
