version: "3.8"

services:
  webapp:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data

  airflow:
    image: apache/airflow:2.7.1
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
    ports:
      - "8080:8080"
    command: ["webserver"]
